### ISSUE TITLE
distance function

### ISSUE THREAD

**Issue by ghost** [erogol/RSOM#2]
The current chessboard (Manhattan) distance used when updating units is not very good.
Just thought I should share the one I'm using:

`
    def euclideanDistanceOnHexagonalToroidMap(self, som_x, som_y, x, y):

```
    x1 = min(som_x, x)

    y1 = min(som_y, y)

    x2 = max(som_x, x)

    y2 = max(som_y, y)

    xdist = min(x2 - x1, x1 + self.height - x2)

    ydist = min(y2 - y1, y1 + self.width - y2)

    if int(ydist) & 1:

        xdist += (-0.5 if (int(y1) & 1) else 0.5)

    return sqrt(float(xdist * xdist + ydist * ydist))`
```

**Comment by erogol** [comment]
Thanks for return maybe you can convert it to a pull request.
