### ISSUE TITLE
alpha variable does nothing

### ISSUE THREAD

**Issue by ghost** [erogol/RSOM#3]
In set_params() in for loop the alpha variable does nothing it seems, you can set it to anything you want and output is unchanged, except 0. When set to 0 everything stops working, otherwise no change in output whatsoever.

**Comment by erogol** [comment]
Thanks for the flag. Unfortunately, I am not following this repo so much any more. However, from a overlook I can say that, alpha seems fine on the code without any problem. Beside this, any pull is welcome if you amend  what you mean?
